/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Entry.java
 *
 * Created on Jul 24, 2013, 2:50:00 PM
 */

package entry;

import addUser.NewUser;
import blockID.BlockID;
import connection.ConnectionDB;
import count.CountBlock;
import getDate.GetDDt;
import java.sql.Statement;
import javax.swing.JOptionPane;
import serialNo.SerialNo;

/**
 *
 * @author BIG BANG
 */
public class Entry extends javax.swing.JFrame {

    /** Creates new form Entry */
    public Entry() {
        initComponents();
        setLocationRelativeTo(null);
        GetDDt t=new GetDDt();
        date.setText(t.getDate());
        time.setText(t.getTime());
        serialNo.SerialNo s=new SerialNo();
        serialNo.setText(s.getSerailNo());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        serialNo = new javax.swing.JTextField();
        carNo = new javax.swing.JTextField();
        category = new javax.swing.JComboBox();
        blockNo = new javax.swing.JComboBox();
        date = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ah = new javax.swing.JLabel();
        bh = new javax.swing.JLabel();
        ch = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        ahw = new javax.swing.JTextField();
        bhw = new javax.swing.JTextField();
        chw = new javax.swing.JTextField();
        dhw = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        alw = new javax.swing.JTextField();
        blw = new javax.swing.JTextField();
        clw = new javax.swing.JTextField();
        dlw = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("PARKING");

        jLabel3.setText("Serial no");

        jLabel4.setText("category");

        jLabel5.setText("Vehicle no");

        jLabel6.setText("Block no");

        jLabel7.setText("Date");

        jLabel8.setText("Time");

        serialNo.setEditable(false);

        category.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HEAVY WEIGHT VEHICLE", "LIGHT WEIGHT VEHICLE" }));

        blockNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        date.setEditable(false);

        time.setEditable(false);

        jButton1.setText("Cancle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel9.setText("BLOCK");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel10.setText("VACANT SLOT");

        ah.setText("A");

        bh.setText("B");

        ch.setText("C");

        d1.setText("D");

        ahw.setEditable(false);

        bhw.setEditable(false);

        chw.setEditable(false);
        chw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chwActionPerformed(evt);
            }
        });

        dhw.setEditable(false);

        jLabel15.setText("LWV");

        jLabel16.setText("HWV");

        a1.setText("A");

        b1.setText("B");

        jLabel19.setText("C");

        jLabel20.setText("D");

        alw.setEditable(false);

        blw.setEditable(false);
        blw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blwActionPerformed(evt);
            }
        });

        clw.setEditable(false);

        dlw.setEditable(false);

        jMenu3.setText("Add User");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu1.setText("Search Vehicle");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(category, 0, 117, Short.MAX_VALUE)
                                    .addComponent(carNo, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(serialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(blockNo, 0, 117, Short.MAX_VALUE)))
                            .addComponent(jLabel2))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(ah)
                                    .addComponent(bh)
                                    .addComponent(ch)
                                    .addComponent(d1))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ahw)
                                    .addComponent(bhw)
                                    .addComponent(chw)
                                    .addComponent(dhw)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(b1)
                                    .addComponent(a1)
                                    .addComponent(jLabel20))
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dlw, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(blw, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(alw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(clw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(142, 142, 142))))
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(345, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(674, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(serialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(carNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bh)
                                    .addComponent(bhw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ah)
                                .addComponent(ahw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d1)
                            .addComponent(dhw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(ch)
                        .addComponent(chw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(blockNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(a1)
                    .addComponent(alw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b1)
                            .addComponent(blw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(clw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(dlw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chwActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(checkVacantBlock())
       {
           JOptionPane.showMessageDialog(null, "BLOCK FULL!!Choose another block");

       }
       else if(cn.checkVehicle(carNo.getText())){
           JOptionPane.showMessageDialog(null, "Already Enterd vehicle of "+carNo.getText()+" no. ");
       }
       else if(!carNo.getText().equals("") ){
        connection.ConnectionDB get=new ConnectionDB();
        Statement stmt=get.connect();
        GetDDt d=new GetDDt();
        int i=0;
        blockID.BlockID gets=new BlockID();


        try {
            String values="'"+serialNo.getText()+"','"+category.getSelectedItem()+"','"+carNo.getText()+"','"+blockNo.getSelectedItem()+"','"+d.getDate()+"','"+d.getTime()+"',"+gets.getBlockID(blockNo.getSelectedItem().toString(), category.getSelectedItem().toString())+"";
           i=stmt.executeUpdate("insert into entry(serialNo,category,carNo,blockNo,date,time,blockID) values("+values+")");
           if(i>0){

               JOptionPane.showMessageDialog(null, "Sucessfully Entered");

        CountBlock cb=new CountBlock();
carNo.setText("");
ahw.setText("("+cb.getVacantSlot("AL")+")");
bhw.setText("("+cb.getVacantSlot("BL")+")");
chw.setText("("+cb.getVacantSlot("CL")+")");
dhw.setText("("+cb.getVacantSlot("DL")+")");

alw.setText("("+cb.getVacantSlot("AH")+")");
blw.setText("("+cb.getVacantSlot("BH")+")");
clw.setText("("+cb.getVacantSlot("CH")+")");
dlw.setText("("+cb.getVacantSlot("DH")+")");
carNo.setText("");
 serialNo.SerialNo s=new SerialNo();
        serialNo.setText(s.getSerailNo());
           }else{
               JOptionPane.showMessageDialog(null, "Failed While Updating");
           }
        } catch (Exception e) {
        e.printStackTrace();
        }
       }
       else{
           JOptionPane.showMessageDialog(null, "Vehicle No. required");
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    public boolean checkVacantBlock(){
        if((alw.getText().equals("(0)") && blockNo.getSelectedItem().equals("A") &&
                category.getSelectedItem().equals("HEAVY WEIGHT VEHICLE")) ||
                ( blw.getText().equals("(0)") && blockNo.getSelectedItem().equals("B") && category.getSelectedItem().equals("HEAVY WEIGHT VEHICLE"))
                ||( clw.getText().equals("(0)") && blockNo.getSelectedItem().equals("C") && category.getSelectedItem().equals("HEAVY WEIGHT VEHICLE"))||
                (dlw.getText().equals("(0)") && blockNo.getSelectedItem().equals("D") && category.getSelectedItem().equals("HEAVY WEIGHT VEHICLE"))
                || (ahw.getText().equals("(0)") && blockNo.getSelectedItem().equals("A") && category.getSelectedItem().equals("LIGHT WEIGHT VEHICLE") )||
                (bhw.getText().equals("(0)") && blockNo.getSelectedItem().equals("B") && category.getSelectedItem().equals("LIGHT WEIGHT VEHICLE")
                )|| (chw.getText().equals("(0)") && blockNo.getSelectedItem().equals("C") && category.getSelectedItem().equals("LIGHT WEIGHT VEHICLE")
                )|| (dhw.getText().equals("(0)") && blockNo.getSelectedItem().equals("D") && category.getSelectedItem().equals("LIGHT WEIGHT VEHICLE")))
        {
            return true;
        }
        else{
        return false;
        }
    }
    private void blwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blwActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        CountBlock cb=new CountBlock();
carNo.setText("");
ahw.setText("("+cb.getVacantSlot("AL")+")");
bhw.setText("("+cb.getVacantSlot("BL")+")");
chw.setText("("+cb.getVacantSlot("CL")+")");
dhw.setText("("+cb.getVacantSlot("DL")+")");

alw.setText("("+cb.getVacantSlot("AH")+")");
blw.setText("("+cb.getVacantSlot("BH")+")");
clw.setText("("+cb.getVacantSlot("CH")+")");
dlw.setText("("+cb.getVacantSlot("DH")+")");
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        carNo.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        this.setVisible(false);
        new loginPanel.Login().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.setVisible(false);
        new search.SearchVehicle().setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        this.setVisible(false);
        new exit.Exit().setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        this.setVisible(false);
        new NewUser().setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entry().setVisible(true);
            }
        });
    }
CheckNo cn=new CheckNo();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel ah;
    private javax.swing.JTextField ahw;
    private javax.swing.JTextField alw;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel bh;
    private javax.swing.JTextField bhw;
    private javax.swing.JComboBox blockNo;
    private javax.swing.JTextField blw;
    private javax.swing.JTextField carNo;
    private javax.swing.JComboBox category;
    private javax.swing.JLabel ch;
    private javax.swing.JTextField chw;
    private javax.swing.JTextField clw;
    private javax.swing.JLabel d1;
    private javax.swing.JTextField date;
    private javax.swing.JTextField dhw;
    private javax.swing.JTextField dlw;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu logout;
    private javax.swing.JTextField serialNo;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables

}
